### ISSUE TITLE
howto compile without apoc ?

### ISSUE THREAD

**Issue by hunter688** [Fexcraft/FlansMod#12]
When try to compile, it fail because apoc errors. (incomplete port)

Howto compile without apoc?

**Comment by Fexcraft** [comment]
Remove the 'apocalipse' folder from the workspace (/src/main/java/etc/).

Thought you can't use this as jar file yet, cause something in the gun render isn't done and will crash (obsfucation?).
It works fine in Eclipse though.

**Comment by hunter688** [comment]
Thanks a lot!

**Comment by hunter688** [comment]
looks like work, but must change manually change:

<pre>
[hunterz@dusan model]$ git diff ArmModelRenderer.java
diff --git a/src/main/java/com/flansmod/client/model/ArmModelRenderer.java b/src/main/java/com/flansmod/client/model/ArmModelRenderer.java
index ddeaf6a..1025e59 100644
--- a/src/main/java/com/flansmod/client/model/ArmModelRenderer.java
+++ b/src/main/java/com/flansmod/client/model/ArmModelRenderer.java
@@ -101,7 +101,7 @@ public class ArmModelRenderer extends ModelRenderer
         result.add((ArmModelRenderer) modelBase.bipedRightArm);
 
         //armors
-        List<LayerRenderer> layerRenderers = ReflectionUtils.getValue(RenderLivingBase.class, renderer, "layerRenderers"); //TODO: obfuscated
+        List<LayerRenderer> layerRenderers = ReflectionUtils.getValue(RenderLivingBase.class, renderer, "field_177097_h"); //TODO: obfuscated
         for (LayerRenderer layerRenderer : layerRenderers)
         {
             if (!(layerRenderer instanceof LayerArmorBase))
@@ -146,7 +146,7 @@ public class ArmModelRenderer extends ModelRenderer
         result.add((ArmModelRenderer) modelBase.bipedLeftArm);
 
         //armors
-        List<LayerRenderer> layerRenderers = ReflectionUtils.getValue(RenderLivingBase.class, renderer, "layerRenderers");
+        List<LayerRenderer> layerRenderers = ReflectionUtils.getValue(RenderLivingBase.class, renderer, "field_177097_h");
         for (LayerRenderer layerRenderer : layerRenderers)
         {
             if (!(layerRenderer instanceof LayerArmorBase))
@@ -190,7 +190,7 @@ public class ArmModelRenderer extends ModelRenderer
         }
 
         //armors
-        List<LayerRenderer> layerRenderers = ReflectionUtils.getValue(RenderLivingBase.class, renderer, "layerRenderers"); //TODO: obfuscated
+        List<LayerRenderer> layerRenderers = ReflectionUtils.getValue(RenderLivingBase.class, renderer, "field_177097_h"); //TODO: obfuscated
         for (LayerRenderer layerRenderer : layerRenderers)
         {
             if (!(layerRenderer instanceof LayerArmorBase))
@@ -230,7 +230,7 @@ public class ArmModelRenderer extends ModelRenderer
         }
 
         //armors
-        List<LayerRenderer> layerRenderers = ReflectionUtils.getValue(RenderLivingBase.class, renderer, "layerRenderers"); //TODO: obfuscated
+        List<LayerRenderer> layerRenderers = ReflectionUtils.getValue(RenderLivingBase.class, renderer, "field_177097_h"); //TODO: obfuscated
         for (LayerRenderer layerRenderer : layerRenderers)
         {
             if (!(layerRenderer instanceof LayerArmorBase))

</pre>

Then jar works.

Looks like need some obf before build.

**Comment by TypicalDarkness** [comment]
If you are using Intellij Idea you can also mark the apoc package as ignored (probably also works on eclipse but I don't know how)

**Comment by Fexcraft** [comment]
I think he meant the gradle compiling to get a jar though?
(also the compiled jar was broken for mee, cause of obsfucation thing)

Cause it will launch in eclipse even with apocalypse files being there since all/most refferences to broken files are commented out or ignored as long not used ingame.

**Comment by TypicalDarkness** [comment]
Oh ok. I will fix the obfuscated reflection when I come home in 2 days.

**Comment by hunter688** [comment]
thanks

**Comment by TypicalDarkness** [comment]
This is probably a stupid question, but how do I compile the mod? This is the error I get when running gradle build:

```
warning: [options] bootstrap class path not set in conjunction with -source 1.6
ClientProxyApocalypse.java:58: error: method references are not supported in -source 1.6
		RenderingRegistry.registerEntityRenderingHandler(EntityAIMecha.class, RenderMecha::new);
		                                                                                   ^
  (use -source 8 or higher to enable method references)
ClientProxy.java:192: error: method references are not supported in -source 1.6
		RenderingRegistry.registerEntityRenderingHandler(EntityBullet.class, RenderBullet::new);
		                                                                                   ^
  (use -source 8 or higher to enable method references)
OverrideVanillaModelLoader.java:47: error: diamond operator is not supported in -source 1.6
    private final HashMap<ResourceLocation, InfoType> acceptedTypes = new HashMap<>();
                                                                                  ^
  (use -source 7 or higher to enable diamond operator)
IFlanItem.java:15: error: default methods are not supported in -source 1.6
	default RenderCustomItem getRenderItemEntity()
	
  (use -source 8 or higher to enable default methods)
4 errors
1 warning
:compileJava FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':compileJava'.
> Compilation failed; see the compiler error output for details.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED
```

How do I compile with 1.8 ?

**Comment by Fexcraft** [comment]
I guess this needed an edit in the build.gradle file, which and where I don't remember, don't have access to the files atm. (pc off/packed)

You could try:
Download latest 1.10 forge mdk, unpack it, and copy the code for the build.gradle file from there or override the file (the original has some custom tasks to put the content packs into jars though).

_might be not availe the next days_

**Comment by hunter688** [comment]
gradle fix:

<pre>
diff --git a/build.gradle b/build.gradle
index 1d7f93c..c69f850 100644
--- a/build.gradle
+++ b/build.gradle
@@ -12,6 +12,12 @@ buildscript {
 }
 apply plugin: 'net.minecraftforge.gradle.forge'
 
+apply plugin: 'java'
+  compileJava {
+  sourceCompatibility = '1.8'
+  targetCompatibility = '1.8'
+}
+
 version = "5.2"
 group= "com.flansmod"
 archivesBaseName = "Flan's Mod"
</pre>

**Comment by Fexcraft** [comment]
ye, source/target compatibility was it

**Comment by TypicalDarkness** [comment]
Is there a way to export FexLib automatically during building?

**Comment by Fexcraft** [comment]
It's already a jar?
Just copy to mods folder and should work.
