### ISSUE TITLE
build.gradle is boken

### ISSUE THREAD

**Issue by Tsoccerguy3** [Fexcraft/FlansMod#25]
Just updated Forge version and MCP mappings and ran gradle build .
crash log 
`This mapping 'snapshot_20170206' was designed for MC 1.11! Use at your own peril.This mapping 'snapshot_20170206' was designed for MC 1.11! Use at your own peril.

#################################################
         ForgeGradle 2.2-SNAPSHOT-2112b0a        
  https://github.com/MinecraftForge/ForgeGradle  
#################################################
               Powered by MCP unknown               
             http://modcoderpack.com             
         by: Searge, ProfMobius, Fesh0r,         
         R4wk, ZeuX, IngisKahn, bspkrs           
#################################################
:deobfCompileDummyTask
:getVersionJson
:extractUserdev
Download http://files.minecraftforge.net/maven/net/minecraftforge/forge/1.11.2-13.20.0.2227/forge-1.11.2-13.20.0.2227.pom
Download http://files.minecraftforge.net/maven/net/minecraftforge/forge/1.11.2-13.20.0.2227/forge-1.11.2-13.20.0.2227-userdev.jar
:downloadClient SKIPPED
:downloadServer SKIPPED
:splitServerJar SKIPPED
:mergeJars SKIPPED
:applyBinaryPatches
:deobfProvidedDummyTask
:extractDependencyATs SKIPPED
:extractMcpData SKIPPED
:extractMcpMappings
Download http://files.minecraftforge.net/maven/de/oceanlabs/mcp/mcp_snapshot/20170206-1.11/mcp_snapshot-20170206-1.11.zip
:genSrgs
:deobfMcMCP
Applying SpecialSource...
Applying Exceptor...
:sourceApiJava
:compileApiJava UP-TO-DATE
:processApiResources UP-TO-DATE
:apiClasses UP-TO-DATE
:sourceMainJava
:compileJavaC:\Users\ASUS\Dev\FlansMod\build\sources\main\java\com\flansmod\common\data\DriveableData.java:165: error: non-static method getNewKeyCode() cannot be referenced from a static context
				lock_code = KeyItem.getNewKeyCode();
				                   ^
C:\Users\ASUS\Dev\FlansMod\build\sources\main\java\com\flansmod\client\debug\UtilGui.java:15: error: cannot find symbol
			mc.fontRendererObj.drawStringWithShadow(n0, 4, 4, 0x90C3D4);
			  ^
  symbol:   variable fontRendererObj
  location: variable mc of type Minecraft
C:\Users\ASUS\Dev\FlansMod\build\sources\main\java\com\flansmod\client\debug\UtilGui.java:16: error: cannot find symbol
			mc.fontRendererObj.drawStringWithShadow(n1, 4, 12, 0x90C3D4);
			  ^
  symbol:   variable fontRendererObj
  location: variable mc of type Minecraft
C:\Users\ASUS\Dev\FlansMod\build\sources\main\java\com\flansmod\client\debug\UtilGui.java:17: error: cannot find symbol
			mc.fontRendererObj.drawStringWithShadow(n2, 4, 20, 0x90C3D4);
			  ^
  symbol:   variable fontRendererObj
  location: variable mc of type Minecraft
C:\Users\ASUS\Dev\FlansMod\build\sources\main\java\com\flansmod\client\debug\UtilGui.java:18: error: cannot find symbol
			mc.fontRendererObj.drawStringWithShadow(n3, 4, 28, 0x90C3D4);
			  ^
  symbol:   variable fontRendererObj
  location: variable mc of type Minecraft
C:\Users\ASUS\Dev\FlansMod\build\sources\main\java\com\flansmod\client\debug\UtilGui.java:19: error: cannot find symbol
			mc.fontRendererObj.drawStringWithShadow(n4, 4, 36, 0x90C3D4);
			  ^
  symbol:   variable fontRendererObj
  location: variable mc of type Minecraft
C:\Users\ASUS\Dev\FlansMod\build\sources\main\java\com\flansmod\client\debug\UtilGui.java:20: error: cannot find symbol
			mc.fontRendererObj.drawStringWithShadow(n5, 4, 44, 0x90C3D4);
			  ^
  symbol:   variable fontRendererObj
  location: variable mc of type Minecraft
C:\Users\ASUS\Dev\FlansMod\build\sources\main\java\com\flansmod\client\debug\UtilGui.java:21: error: cannot find symbol
			mc.fontRendererObj.drawStringWithShadow(n6, 4, 52, 0x90C3D4);
			  ^
  symbol:   variable fontRendererObj
  location: variable mc of type Minecraft
C:\Users\ASUS\Dev\FlansMod\build\sources\main\java\com\flansmod\client\debug\UtilGui.java:22: error: cannot find symbol
			mc.fontRendererObj.drawStringWithShadow(n7, 4, 60, 0x90C3D4);
			  ^
  symbol:   variable fontRendererObj
  location: variable mc of type Minecraft
C:\Users\ASUS\Dev\FlansMod\build\sources\main\java\com\flansmod\client\gui\GuiDriveableFuel.java:38: error: cannot find symbol
		fontRendererObj.drawString(plane.getDriveableType().name + " - Fuel", 6, 6, 0x404040);
		^
  symbol:   variable fontRendererObj
  location: class GuiDriveableFuel
C:\Users\ASUS\Dev\FlansMod\build\sources\main\java\com\flansmod\client\gui\GuiDriveableFuel.java:39: error: cannot find symbol
		fontRendererObj.drawString("Inventory", 8, (ySize - 96) + 2, 0x404040);
		^
  symbol:   variable fontRendererObj
  location: class GuiDriveableFuel
C:\Users\ASUS\Dev\FlansMod\build\sources\main\java\com\flansmod\client\gui\GuiDriveableInventory.java:51: error: cannot find symbol
		fontRendererObj.drawString(driveable.getDriveableType().name + title, 6, 6, 0x404040);
		^
  symbol:   variable fontRendererObj
  location: class GuiDriveableInventory
C:\Users\ASUS\Dev\FlansMod\build\sources\main\java\com\flansmod\client\gui\GuiDriveableInventory.java:52: error: cannot find symbol
		fontRendererObj.drawString("Inventory", 8, (ySize - 96) + 2, 0x404040);
		^
  symbol:   variable fontRendererObj
  location: class GuiDriveableInventory
C:\Users\ASUS\Dev\FlansMod\build\sources\main\java\com\flansmod\client\gui\GuiDriveableInventory.java:75: error: cannot find symbol
		itemRender.renderItemOverlayIntoGUI(fontRendererObj, itemstack, i, j, null);
		                                    ^
  symbol:   variable fontRendererObj
  location: class GuiDriveableInventory
C:\Users\ASUS\Dev\FlansMod\build\sources\main\java\com\flansmod\client\gui\GuiDriveableMenu.java:106: error: cannot find symbol
		fontRendererObj.drawString(entity.getDriveableType().name + " [CODE: " + entity.driveableData.lock_code.toUpperCase() + "]", 6, 6, 0x404040);
		^
  symbol:   variable fontRendererObj
  location: class GuiDriveableMenu
C:\Users\ASUS\Dev\FlansMod\build\sources\main\java\com\flansmod\client\gui\GuiDriveableMenu.java:107: error: cannot find symbol
		fontRendererObj.drawString("Inventory", 8, (ySize - 96) + 2, 0x404040);
		^
  symbol:   variable fontRendererObj
  location: class GuiDriveableMenu
C:\Users\ASUS\Dev\FlansMod\build\sources\main\java\com\flansmod\client\gui\GuiDriveableRepair.java:115: error: cannot find symbol
		drawString(fontRendererObj, driving.getDriveableType().name + " - Repair", guiOriginX + 7, guiOriginY + 7, 0xffffff);
		           ^
  symbol:   variable fontRendererObj
  location: class GuiDriveableRepair
C:\Users\ASUS\Dev\FlansMod\build\sources\main\java\com\flansmod\client\gui\GuiDriveableRepair.java:133: error: cannot find symbol
			drawString(fontRendererObj, part.type.getName(), guiOriginX + 10, guiOriginY + y + 6, 0xffffff);
			           ^
  symbol:   variable fontRendererObj
  location: class GuiDriveableRepair
C:\Users\ASUS\Dev\FlansMod\build\sources\main\java\com\flansmod\client\gui\GuiDriveableRepair.java:134: error: cannot find symbol
			drawCenteredString(fontRendererObj, (int)(percentHealth * 100F) + "%", guiOriginX + 158, guiOriginY + y + 6, 0xffffff);
			                   ^
  symbol:   variable fontRendererObj
  location: class GuiDriveableRepair
C:\Users\ASUS\Dev\FlansMod\build\sources\main\java\com\flansmod\client\gui\GuiDriveableRepair.java:219: error: cannot find symbol
		itemRenderer.renderItemOverlayIntoGUI(fontRendererObj, itemstack, i, j, null);
		                                      ^
  symbol:   variable fontRendererObj
  location: class GuiDriveableRepair
C:\Users\ASUS\Dev\FlansMod\build\sources\main\java\com\flansmod\common\network\handlers\DriveableControlPacketHandler.java:28: error: cannot find symbol
					EntityPlayerMP player = FMLCommonHandler.instance().getMinecraftServerInstance().getPlayerList().getPlayerByUsername(ctx.getServerHandler().playerEntity.getName());
					                                                                                                                                           ^
  symbol:   variable playerEntity
  location: class NetHandlerPlayServer
C:\Users\ASUS\Dev\FlansMod\build\sources\main\java\com\flansmod\common\network\handlers\DriveableKeyHeldPacketHandler.java:21: error: cannot find symbol
				EntityPlayerMP player = FMLCommonHandler.instance().getMinecraftServerInstance().getPlayerList().getPlayerByUsername(ctx.getServerHandler().playerEntity.getName());
				                                                                                                                                           ^
  symbol:   variable playerEntity
  location: class NetHandlerPlayServer
C:\Users\ASUS\Dev\FlansMod\build\sources\main\java\com\flansmod\common\network\handlers\DriveableKeyPacketHandler.java:21: error: cannot find symbol
				EntityPlayerMP player = FMLCommonHandler.instance().getMinecraftServerInstance().getPlayerList().getPlayerByUsername(ctx.getServerHandler().playerEntity.getName());
				                                                                                                                                           ^
  symbol:   variable playerEntity
  location: class NetHandlerPlayServer
C:\Users\ASUS\Dev\FlansMod\build\sources\main\java\com\flansmod\common\network\handlers\DriveableSyncPacketHandler.java:27: error: cannot find symbol
					EntityPlayerMP player = FMLCommonHandler.instance().getMinecraftServerInstance().getPlayerList().getPlayerByUsername(ctx.getServerHandler().playerEntity.getName());
					                                                                                                                                           ^
  symbol:   variable playerEntity
  location: class NetHandlerPlayServer
C:\Users\ASUS\Dev\FlansMod\build\sources\main\java\com\flansmod\common\network\handlers\PlaneControlPacketHandler.java:25: error: cannot find symbol
					EntityPlayerMP player = FMLCommonHandler.instance().getMinecraftServerInstance().getPlayerList().getPlayerByUsername(ctx.getServerHandler().playerEntity.getName());
					                                                                                                                                           ^
  symbol:   variable playerEntity
  location: class NetHandlerPlayServer
C:\Users\ASUS\Dev\FlansMod\build\sources\main\java\com\flansmod\common\network\handlers\SeatUpdatePacketHandler.java:28: error: cannot find symbol
					EntityPlayerMP player = FMLCommonHandler.instance().getMinecraftServerInstance().getPlayerList().getPlayerByUsername(ctx.getServerHandler().playerEntity.getName());
					                                                                                                                                           ^
  symbol:   variable playerEntity
  location: class NetHandlerPlayServer
C:\Users\ASUS\Dev\FlansMod\build\sources\main\java\com\flansmod\common\network\handlers\VehicleControlPacketHandler.java:26: error: cannot find symbol
					EntityPlayerMP player = FMLCommonHandler.instance().getMinecraftServerInstance().getPlayerList().getPlayerByUsername(ctx.getServerHandler().playerEntity.getName());
					                                                                                                                                           ^
  symbol:   variable playerEntity
  location: class NetHandlerPlayServer
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: Some input files use unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
27 errors
 FAILED`

**Comment by Fexcraft** [comment]
I didn't update the mappings to work with 1.11.2 as far as I recall.

**Comment by Fexcraft** [comment]
Forgot that I updated the mappings some commits ago.
